name: Create Release

on:
  push:
    branches: 
      - main
    paths-ignore:
      - '.github/**'
    types:
      - pushed

jobs:
  release:
    if: contains(github.event.head_commit.message, 'release')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x' # Adjust this to your .NET version

      - name: Build project
        run: dotnet publish -c Release -r win-x64 --self-contained

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.sha }}
          release_name: Release ${{ github.sha }}
          draft: false
          prerelease: false

      - name: Upload .exe file
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/Release/net6.0/win-x64/publish/Game-Maker.exe # Adjust this to your .exe file path
          asset_name: Game-Maker.exe # Adjust this to your .exe file name
          asset_content_type: application/octet-stream
